routes/admin_routes.py
import time
import logging
import ast
from datetime import datetime
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    get_flashed_messages,
    abort,
    session,
)
from flask_login import current_user, login_required
from pymongo import UpdateOne
from bson.objectid import ObjectId
from utilities.pymongo.collections.DimMovies import MDBDimMovies
from utilities.pymongo.collections.DimClues import MDBDimClues
from utilities.get_movie_neighbors import get_movie_neighbors
from utilities.chatGPT.gpt_requests import get_twisted_title_description
from utilities.validate_clue import validate_clue
from utilities.global_utils import remove_non_alpha_letters, get_max_string_key_value

# Create a Blueprint
admin_blueprint = Blueprint("admin", __name__)

# --------------- ROUTE UTILITIES --------------- #
def check_admin():
    if current_user.is_admin == False or current_user.is_admin == None:
        return redirect(url_for("auth.profile"))


def check_for_clue_errors(movie_id, twist_title, validation_errors):
    if len(validation_errors) > 0:
        errors = [x.message for x in validation_errors]
        logging.info(f"Clue validation errors: {errors}")
        flash((movie_id, twist_title, " | ".join(errors)), "clue_validation_error")
        abort(redirect(url_for("admin.create_clues")))
    return

def assign_filter(filter_set: str, field_name: str, session=session) -> None:
    """
    This function is used to assign a filter to the session object.
    """
    if request.form.get(field_name):
        session[filter_set][field_name] = request.form.get(field_name)
    else:
        session[filter_set].pop(field_name, None)
    return

# --------------- TEMPLATE FILTERS --------------- #
@admin_blueprint.app_template_filter('from_unix')
def convert_from_unix(s):
    """
    Convert a unix timestamp to a human readable time.
    """
    return datetime.fromtimestamp(s).strftime('%Y-%m-%d %H:%M:%S')

@admin_blueprint.app_template_filter('highlight_difference')
def highlight_difference(mod: str, orig: str, is_orig: bool) -> str:
    """
    Compare two strings and wrap the differing character in a <span> tag.
    """
    class_mod = "highlight-good" if is_orig else "highlight-bad"
    if len(orig) != len(mod):
        return mod 
    result = []
    for c1, c2 in zip(orig, mod):
        if c1 == c2:
            result.append(c2)
        else:
            result.append(f'<span class="{class_mod}">{c2}</span>')  # Wrap different character
    return ''.join(result)


# --------------- BLUEPRINT ROUTES --------------- #
@admin_blueprint.route("/create_clues", methods=["GET", "POST"])
@login_required
def create_clues(**kwargs):
    """
    This function is used to create clues for the movies.
    """

    check_admin()
    # Only generate the movie list if the on first load.
    # This makes sure that a reloaded page can keep current set of movies on the page.
    # Get all movies sorting by active clue count and vote count.
    # movie_db = MDBDimMovies()
    with MDBDimMovies() as movie_db:
        movie_list = dict({})
        movie_update_requests = []

        filters = session.get("movie_search_filters", dict({}))
        difficulties = [x for x in filters.pop("difficulty", [1, 2, 3]) if x is not None]
        max_movie_return = 12
        if len(difficulties) != 0:
            diff_batch_count = max_movie_return // len(difficulties)

            # Get 4 movies from each difficult
            for i in difficulties:
                filters['difficulty'] = i
                movies = movie_db.collection.find(
                    filter=filters,
                    sort={"admin_ind_has_clue": 1, "vote_count": -1},
                    limit=diff_batch_count,
                )

                if movies == None:
                    logging.warning("No movies found in mongo Response - Breaking")
                    break

                for m in movies:
                    # if the word neighbors are not in the movie record, get them, should only run first time
                    if m.get("word_neighbors") == None:
                        m["word_neighbors"] = dict()
                        for word in m["title"].split():
                            m["word_neighbors"][word] = get_movie_neighbors(word)
                        movie_update_requests.append(
                            UpdateOne(
                                {"id": m["id"]},
                                {"$set": {"word_neighbors": m["word_neighbors"]}},
                            )
                        )
                    movie_list[m["id"]] = m

        # reset difficulty filter
        filters['difficulty'] = difficulties

        # update mongoDB with any new word neighbors if necessary
        if len(movie_update_requests) > 0:
            logging.info(f"{len(movie_update_requests)} records to be updated in MongoDB.")
            update = movie_db.collection.bulk_write(movie_update_requests)
            logging.info(
                f"Updated with {update.modified_count} records with word neighbors."
            )

    gpt_response = get_flashed_messages(category_filter=["gpt_response"])
    if gpt_response:
        gpt_response = gpt_response[0]

    if gpt_response and gpt_response[0] in movie_list:
        logging.info(
            "Adding GPT response to the movie list to populate description text area."
        )
        movie_id = gpt_response[0]
        movie_list[movie_id]["gpt_response"] = gpt_response[2]
        movie_list[movie_id]["twist_clue_attempt"] = gpt_response[1]

    # page load errors
    clue_errors = get_flashed_messages(category_filter=["clue_validation_error"])
    if clue_errors and clue_errors[0] in movie_list:
        clue_errors = clue_errors[0]
        movie_id = clue_errors[0]
        movie_list[movie_id]["twist_clue_attempt"] = clue_errors[1]
        movie_list[movie_id]["clue_error"] = clue_errors[2]

    clue_proposal_success = get_flashed_messages(category_filter=["clue_proposal_success"])
    if clue_proposal_success and clue_proposal_success[0] in movie_list:
        clue_proposal_success = clue_proposal_success[0]
        movie_id = clue_proposal_success[0]
        movie_list[movie_id]["twist_clue_attempt"] = clue_proposal_success[1]
        movie_list[movie_id]["clue_proposal_success"] = clue_proposal_success[2]

    return render_template(
        "create_clues.html",
        current_user=current_user,
        movie_list=movie_list,
        filters=filters,
    )


@admin_blueprint.route("/update_movies", methods=["POST"])
@login_required
def update_movies():
    """
    This function is used to update the clue information in the database.
    """

    movie_id = int(request.form.get("movie_id"))
    original_title = request.form.get("movie_title")
    twist_title = request.form.get("twisted_title", "").upper()
    raw_twist_title = remove_non_alpha_letters(twist_title)

    # Check if submitted title is valid
    logging.info("Firing clue validation process")
    validation_errors = validate_clue(
        original_movie=original_title, modified_movie=twist_title
    )

    # Generate a chat GPT description
    if "generate_gpt_response" in request.form:
        filtered_errors = [
            x
            for x in validation_errors
            if "generate_gpt_response" in x.scope and x.action != "BLOCK"
        ]
        print(len(filtered_errors))
        check_for_clue_errors(movie_id, twist_title, filtered_errors)
        result = get_twisted_title_description(
            original_movie=original_title,
            modified_movie=twist_title,
        )
        # flash the result to the next response page
        flash((movie_id, twist_title, result), "gpt_response")
        redirect(url_for("admin.create_clues"))

    elif "save_movie_attr" in request.form:

        print(request.form)
        # Connect to the database
        with MDBDimMovies() as movie_db:

            # Get the update information
            deprioritize_flag = (
                True if request.form.get("deprioritize_flag") == "on" else False
            )

            # Send update commmand to Mongo DB
            result = movie_db.collection.update_one(
                {"id": movie_id},
                {"$set": {"admin_ind_twisted_depri": deprioritize_flag}},
            )
            if result.modified_count == 0:
                logging.warning(
                    f"Movie {movie_id} not updated - Records found in upated query: {result.matched_count}"
                )
            else:
                logging.info(
                    f"{result.matched_count} found: {result.modified_count} record updated. Movie {movie_id} modified."
                )

    elif "propose_clue" in request.form:

        # Check if submitted title is valid
        logging.info("Firing clue validation process")
        filtered_errors = []
        description_contains_title = False
        for x in validation_errors:
            filtered_errors.append(x)
            if x.code == "CLUE_HAS_TITLE":
                description_contains_title = True

        check_for_clue_errors(movie_id, twist_title, filtered_errors)

        # Connect to the database
        with MDBDimClues() as clues_db:

            # Send update commmand to Mongo DB
            result = clues_db.collection.find_one(
                filter={
                    "movie_id": movie_id,
                    "raw_twist_title": raw_twist_title,
                }
            )
            if result:
                flash(
                    (
                        movie_id,
                        twist_title,
                        f"Title '{twist_title}' already exists as a clue.",
                    ),
                    "clue_proposal_error",
                )

            else:
                result = clues_db.collection.insert_one(
                    document={
                        "movie_id": movie_id,

routes/auth_routes.py
import logging
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from flask_login import login_user, current_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from models.user import User
from extensions import twisted_db

# Create a Blueprint
auth_blueprint = Blueprint("auth", __name__)

@auth_blueprint.route('/profile')
@login_required
def profile():
    return render_template(
        'profile.html',
        current_user=current_user,
        )
    
@auth_blueprint.route('/login', methods=['POST', 'GET'])
def login():
    error = None
    if current_user.is_authenticated:
        return redirect(url_for('game.index'))
    
    form_username = request.form.get('username')
    form_password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = twisted_db.session.execute(
        twisted_db.select(User).filter_by(username = form_username)
        ).scalar_one_or_none()
    
    if request.method == 'POST':
        if not user: 
            logging.warning('user attempted username does not exist in database.')
            error = 'No matching accounts with given username. Please try again or register as new user.'
        elif check_password_hash(user.password, form_password):
            logging.info('User successfully logged into account.')
            login_user(user, remember=remember)
            return redirect(url_for('game.index'))
        elif check_password_hash(user.password, form_password) == False:
            logging.warning('user attempted username/password combo does not match.')
            error = 'Invalid credentials. Please try again.'
    if error:
        flash(error)
    return redirect(url_for('game.index'))
    

@auth_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    
    if request.method == 'GET':
        # check to see if current user is authenticated
        if current_user.is_authenticated:
            return redirect(url_for('game.index'))
        return render_template('register.html') 
    
    username = request.form.get('username')
    password = request.form.get('password')
    confirm_password = request.form.get('confirm_password')
    first_name = request.form.get('first_name')

    # User Registration form validation
    errors = []
    
    # check if user / username already exists in databse
    user_username = twisted_db.session.execute(
        twisted_db.select(User).filter_by(username = username)
        ).scalar_one_or_none()
    if user_username:
        errors.append('Username already registered with another accounts.')
    if password != confirm_password:
        errors.append('Passwords do not match, pease try again.')
    
    # move on if no errors
    if len(errors) == 0:
        new_user = User(
            username=username,
            password = generate_password_hash(password, method='scrypt'),
            first_name = first_name,
            is_admin = False
            )
        twisted_db.session.add(new_user)
        twisted_db.session.commit()
        user = twisted_db.session.execute(
            twisted_db.select(User).filter_by(username = username)
            ).scalar_one_or_none()
        login_user(user, remember=False)
        return redirect(url_for('game.index'))
    else:
        for error in errors:
            flash(error)
        return redirect(url_for('game.index'))



@auth_blueprint.route('/logout')
@login_required
def logout():
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('game.index'))
    else:
        return render_template(
            'index.html',
            current_user_authenticated = current_user.is_authenticated,
            user_username = current_user.username,
        )

routes/game_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from flask_login import current_user
from assets.title_prompts import title_prompts

MAX_ATTEMPTS = 3

# Create a Blueprint
game_blueprint = Blueprint("game", __name__)

@game_blueprint.route("/", methods=["GET", "POST"])
def index():

    clue = title_prompts[1]

    if "attempt" not in session:
        session["attempt_list"] = {i:{"answer":None,"correct":None} for i in range(1,MAX_ATTEMPTS+1)}
        session["attempt"] = 0
        session["game_over"] = False
        
    # check the user answer
    if request.method == "POST":

        # if session has hit max attempts to answer
        if session["game_over"]:
            # redirect to home page with 
            return redirect(url_for("game.index"))

        # if session has hit max attempts to answer
        user_answer = request.form.get("answer", "").strip().upper()
        session["attempt"] += 1
        attempt = str(session["attempt"])
        session["attempt_list"][attempt]['answer'] = user_answer
        
        # if the user answer is correct
        if user_answer == clue.twisted_title.upper():
            session["attempt_list"][attempt]['correct'] = True
            session["game_over"] = True
        

        # if the page loads and the max attempts are reached
        elif session["attempt"] >= MAX_ATTEMPTS:    
            session["attempt_list"][attempt]['correct'] = False
            session["message"] = f"Game Over! The correct answer was '{clue.twisted_title.upper()}'."
            session["game_over"] = True
        
        else:
            session["attempt_list"][attempt]['correct'] = False
        # else:
        #     session["message"] = f"Incorrect! You have {MAX_ATTEMPTS - session['attempt']} attempts left."

        return redirect(url_for("game.index"))
    
    return render_template(
        "index.html", 
        current_user=current_user,
        clue=clue.prompt, 
        message=session.get("message", ""),
        attempt_list=session.get("attempt_list", dict()),
        correct_attempt=session.get("correct_response", None),
        )

@game_blueprint.route("/reset")
def reset():
    session.pop("attempt", None)
    session["game_over"] = False
    session['correct_response'] = None
    session.pop("message", None)
    return redirect(url_for("game.index"))

@game_blueprint.route("/about")
def about():
    return render_template("about.html", current_user=current_user) 

templates/about.html
{% extends "base.html" %}

{% block title %}
<title>Twisted Title - About </title>
{% endblock %}

{% block content %}
    <h1> Meet Twisted Title.</h1>
    <p>We’re puzzlers. Looking for a more riddling game to satisfy a mind hungry for entertainment. Many years ago an unusual round of bar trivia helped spawn the game we now call Twisted Title. If you, like us, want to turn thousands of hours of consumed content into a cheeky brain teaser, we invite you to play.</p>
    <h3>HOW TO PLAY</h3>
    <p>In this game you’ll be given a clue describing the plot of a book, film, or TV show. However, the clue will contain a twist! The clue description will match the title of the work but with 1 letter swapped out to make a new word. The point of the game is to figure out what letter was switched to make the twisted title!!</p>

    <p>Example:</p>
    <table>
        <tbody>
          <tr>
            <th scope="row"><strong>TWISTED CLUE:</strong></th>
            <td>A scientist discovers a way to bring dinosaurs back to life using a DNA from a wheel of very aged cheese.</td>
          </tr>
          <tr>
            <th scope="row"><strong>TWISTED TITLE:</strong></th>
            <td>Jurassic <del>Park</del> <ins>Parm</ins></td>
          </tr>
      </table>

    <br>
    <a class="btn btn-primary" role="button"  href="{{ url_for('game.index') }}">Go Play</a>
{% endblock %}

templates/admin_base.html
{% extends "base.html" %}

{% block styles %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="grid">
        <div>
            <h4 class="is-size-4">{{ current_user.first_name }} Admin Dashboard</h4>
        </div>
        <div>
            <div class="grid">
                <div><a class="button" href="{{ url_for('auth.profile') }}">Go to Profile Page</a></div>
                <div><a class="button" href="{{ url_for('game.index') }}">Go Play</a></div>
            </div>
        </div>
    </div>
</div>
<br>

<div class="tabs is-boxed">
    <ul>
        <li class="is-active">
            <a href="{{ url_for('admin.create_clues') }}">

                <span>Clues</span>
            </a>
        </li>
        <li>
            <a href="">

                <span>Admin</span>
            </a>
        </li>

    </ul>
</div>

{% set active_page = request.endpoint %}

<div class="tabs is-toggle is-toggle-rounded">
    <ul>
        <li class="{% if active_page == 'admin.create_clues' %}is-active{% endif %}">
            <a href="{{ url_for('admin.create_clues') }}"><span>Create Clues</span></a>
        </li>
        <li class="{% if active_page == 'admin.manage_clues' %}is-active{% endif %}">
            <a href="{{ url_for('admin.manage_clues') }}"><span>Manage Clues</span></a>
        </li>
        <li class="{% if active_page == 'admin.assign_clues' %}is-active{% endif %}">
            <a href="{{ url_for('admin.assign_clues') }}"><span>Assign Clues</span></a>
        </li>
    </ul>
</div>

<div class="container">
    {% block admin_activities %}
    {% endblock %}
</div>


{% endblock %}

{% block final_scripts %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" data-theme="light">
    <meta http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    {% block styles %}
    {% endblock %}
    
    {% block title %}
    {% endblock %}

</head>

<body>
    <section class="section">
        <div class="container is-max-desktop">
        
            <nav class="navbar" role="navigation" aria-label="main navigation">
                <div class="navbar-brand">
                    <a class="navbar-item" href="{{ url_for('game.index')}}"><h1 class="title is-1" style="margin-bottom: 0;">Twisted Title</h1></a>
                </div>
                <div class="navbar-menu">
                    <div class="navbar-start">
                        <a class="navbar-item"href="{{ url_for('game.about') }}">About</a>
                    </div>
                </div>
                {% if current_user.is_authenticated == True %}
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-primary" href="{{ url_for('auth.profile') }}">{{ current_user.first_name }}'s Account</a>
                            <a class="button is-light"href="{{ url_for('auth.logout') }}">Log Out</a>
                        </div>
                    </div>
                </div>
                {% endif %}                
            </nav>
            <hr>
            
            <div>
            {% block content %}
            {% endblock %}
            </div>
            <br>
            <br>
            {% if not current_user or current_user.is_authenticated == False %}
                <br>
                <br>
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Want to save your results?</p>
                        <a class="button is-primary is-round" style="margin:1rem;" href="{{ url_for('auth.register') }}">Register</a>
                    </header>
                    <div class="card-content">
                        <form method="post" action="/login">
                            <div class="content">
                                {% with messages = get_flashed_messages() %}
                                {% if messages %}
                                <blockquote style="border-left: 0.3rem solid #B53731;"">
                                    {% for message in messages %}
                                        <p style=" color: inherit;">{{ message }}</p>
                                    {% endfor %}
                                </blockquote>
                                {% endif %}
                                {% endwith %}
                                <p>Login or Register to save your progress, access the clue archive, and generally be a happier person :)</p>
                                
                                <div class="grid">
                                    <div class="cell">
                                        <input class="input is-rounded" type="text" name="username" placeholder="Username" autocomplete="username" id="username" />
                                    </div>
                                    <div class="cell">
                                        <input class="input is-rounded" type="password" name="password" placeholder="Password" id="password" />
                                    </div>
                                </div>
                            
                                <div style="margin: 1rem;">
                                    <div class="grid">
                                        <div>
                                            <label class="checkbox">
                                                <input type="checkbox" name="showPassword" id="showPassword" onclick="viewToggle(['password']);"> Show Password
                                            </label>
                                        </div>
                                        <div>
                                            <label class="checkbox">
                                                <input type="checkbox" name="RememberMe" id="remember"/> Remember Me
                                            </label>
                                        </div>
                                        <div class="buttons">
                                            <input class="input" type="submit" value="Login" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                     <!-- ERROR MESSAGES -->
                    
                    
    
                </div>
            
            {% endif %}
            <div class="fixed-grid has-3-cols">
                <div class="grid">
                    <div class="cell"><a class="button is-text" href="{{ url_for('game.about') }}">about</a></div>
                    <div class="cell"><a class="button is-text" href="">contribute</a></div>
                    <div class="cell"><p class="button is-text">© 2024 ME !</p></div>
                </div>
            </div>
        
        </div>


        <script>
            function viewToggle(ids) {
                ids.forEach(function (id) {
                    var element = document.getElementById(id);
                    if (element) {
                        if (element.type === "password") {
                            element.type = "text";
                        } else {
                            element.type = "password";
                        }
                    }
                });
            }
        </script>
    </section>
{% block final_scripts %}
{% endblock %}
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
<title>Twisted Title</title>
{% endblock %}

{% block content %}

<div class="container">
    <h1 class="title">Clue:</h1>
    <p>{{ clue }}</p>
    <br>
    <h4>Attempts:</h4>
    <ul class="horizontal-list">
    {% for attempt_num, attempt in attempt_list.items() %}
        {% if attempt['correct'] == True %}
        <li class="horizontal-list large-font">✅<strong> - {{ attempt['answer'] }}</strong></li>
        {% elif attempt['correct'] == False %}
        <li class="horizontal-list large-font" style="color:#ce7e7b;">❌ - {{ attempt['answer'] }} </li>
        {% else %}
        <li class="horizontal-list large-font"><strong>&#9711;</strong></li>
        {% endif %}
    {% endfor %}
    </ul>

    {% if message and message != '' %}
    <br>
    <p>{{ message }}</p>
    <br>
    {% else %}
    <br>
    {% endif %}
    {% if not session.get("game_over", False) %}
        <form method="post">
            <div class="columns">
                <div class="column">
                    <input 
                        class="input" 
                        type="text" 
                        id="answer" 
                        name="answer" 
                        placeholder="your guess" 
                        autofocus 
                        required 
                        style="text-transform:uppercase; font-family: monospace;">
                </div>
                <div class="column">
                    <button class="button is-rounded is-fullwidth is-primary" type="submit">Submit</button>
                </div>
            </div>
        </form>
        
        {% else %}
        <div class="fixed-grid has-4-cols">
            <div class="grid">
                <div class="cell">
                    <a class="button is-primary" href="{{ url_for('game.reset') }}">Play Again</a>
                </div>
                <div class="cell is-col-start-4">
                    {% if current_user.is_authenticated %}
                    <a class="button is-primary is-fullwidth" href="{{ url_for('auth.profile') }}">View Your Record</a>
                    {% else %}
                    <a class="button is-fullwidth" href="{{ url_for('auth.login') }}" disabled><i>(Log in to view record)</i></a>
                    {% endif %}
                </div>
            </div>
        </div>

    {% endif %}
</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}

{% block title %}
<title>TT - {{ current_user.username }} Profile </title>
{% endblock %}

{% block content %}
    <h1 class="is-size-1"> Hello {{ current_user.first_name }}</h1>
    <br>
    <p>Game calendar is going to go here</p>
    <br>
    <a class="button"  href="{{ url_for('admin.create_clues') }}">Go to Admin Panel</a>
    <a class="button"  href="{{ url_for('game.index') }}">Go Play</a>
    
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}
<title>Twisted Title</title>
{% endblock %}

{% block content %}
<h3 class="is-size-3">Register your Twisted Title Account</h3>
<br>
<div class="box">
<p><i>NOTE: There is legit no password reset becuase we won't even collect your email address. <br>So, don't forget your password.</i></p>
</div>
<br>
<form method="POST" action="/register">
    <fieldset>
        <label for="first_name">First Name</label>
        <input type="text" name="first_name" placeholder="First Name" autofocus="" id="first_name">
        <br>
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="username" autofocus="" id="username">
        <br>
        <label for="password">Password</label>
        <input type="password" name="password" placeholder="Password" autofocus="" id="password">
        <br>
        <label for="confirm_password"><em>Confirm Password</em></label>
        <input type="password" name="confirm_password" placeholder="Repeat Password" autofocus="" id="confirm_password">
        <br>
        <label><input type="checkbox" onclick="viewToggle(['password','confirm_password']);">Show Passwords</label>
        <br>
        <input type="submit" value="Register Account">
    </fieldset>

</form>

<br>
<br>
<a href="{{ url_for('game.index')}}">Home</a>
</body>
{% endblock %}